repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        exclude: "scripts/|django_stubs_ext/|functional_tests/"
        args: ["--cache-dir=/dev/null", "--no-incremental", "--config-file", "pyproject.toml"]
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--ignore=tests/e2e/test_api.py"]
