version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/code
    ports:
      - "5005:80"
    env_file:
      - .env


  postgres:
    image: postgres:9.6
    ports:
      - "54321:5432"
    env_file:
      - .env
